<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Jonathan David Castillo" />


<title>05. Mudança climática nos locais de ocorrência</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="assets/estilo.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Flora, biomas e clima</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Início</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Etapas
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_depuracao_BR_01.html">01 · Depuração</a>
    </li>
    <li>
      <a href="02_limpeza_complementar_BR_01.html">02 · Limpeza espacial</a>
    </li>
    <li>
      <a href="03_analise_exploratoria.html">03 · Biomas</a>
    </li>
    <li>
      <a href="04_analise_temporal_e_mapas.html">04 · Tempo e registros</a>
    </li>
    <li>
      <a href="05_mudanca_climatica_mata_atlantica.html">05 · Exposição climática</a>
    </li>
  </ul>
</li>
<li>
  <a href="resultados.html">Resultados</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">05. Mudança climática nos locais de
ocorrência</h1>
<h4 class="author">Jonathan David Castillo</h4>

</div>


<div id="nota" class="section level1">
<h1>NOTA</h1>
<p>Infelizmente, este é apenas um exercício prático de compartilhamento
de dados. Os resultados apresentados a seguir não devem ser considerados
conclusivos e estão longe de constituir evidências suficientes de um
padrão ecológico, devido a diferentes limitações estatísticas,
metodológicas e relacionadas ao desenvolvimento da análise.</p>
</div>
<div id="pergunta-e-continuidade-da-análise" class="section level1">
<h1>Pergunta e continuidade da análise</h1>
<p>As localidades registradas para seis espécies da Mata Atlântica
permanecem na mesma classe de Köppen–Geiger sob o clima projetado para o
final do século?</p>
<p>A análise parte das ocorrências que receberam o bioma <strong>Mata
Atlântica na etapa 3</strong>. A etapa 4 descreve sua base temporal e os
contrastes de documentação entre biomas; aqui, o foco passa das séries
de registros para o clima das localidades. Comparamos
<strong>1991–2020</strong> e <strong>2071–2099</strong>, sob
<strong>SSP5-8.5</strong>, com os mapas de Beck et al. (2023).</p>
<p>O resultado mede a exposição dos locais documentados à mudança de
classe climática. Não estima a área de distribuição das espécies, sua
abundância ou sua probabilidade de extinção. O cenário representa uma
trajetória específica; não é uma previsão única do clima futuro.</p>
</div>
<div id="origem-dos-dados-e-espécies-selecionadas"
class="section level1">
<h1>Origem dos dados e espécies selecionadas</h1>
<p>A matriz original da etapa 3 preservava <code>gbifID</code> e
<code>scientificName</code>, mas descartava <code>species</code>. Nesta
reconstrução, os nomes foram recuperados de
<code>Br_01_clean2.csv</code> pelo <code>gbifID</code>, sem criar
ocorrências adicionais. A nova versão da etapa 3 passa a conservar essa
coluna. A cópia portátil desse recorte está em
<code>data/ocorrencias_alvo_etapa03.rds</code>.</p>
<pre class="r"><code>amostra &lt;- d |&gt;
  group_by(species) |&gt;
  summarise(registros=n(),sem_ano=sum(is.na(year)),
            anos=if(all(is.na(year))) &quot;Não informado&quot; else paste(range(year,na.rm=TRUE),collapse=&quot;–&quot;),
            .groups=&quot;drop&quot;)
tab(amostra,col.names=c(&quot;Espécie&quot;,&quot;Registros&quot;,&quot;Sem ano&quot;,&quot;Intervalo de anos&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Espécie</th>
<th align="right">Registros</th>
<th align="right">Sem ano</th>
<th align="left">Intervalo de anos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Araucaria angustifolia</td>
<td align="right">2534</td>
<td align="right">0</td>
<td align="left">2000–2026</td>
</tr>
<tr class="even">
<td align="left">Cariniana legalis</td>
<td align="right">220</td>
<td align="right">0</td>
<td align="left">2000–2026</td>
</tr>
<tr class="odd">
<td align="left">Cattleya labiata</td>
<td align="right">17</td>
<td align="right">0</td>
<td align="left">2002–2026</td>
</tr>
<tr class="even">
<td align="left">Dicksonia sellowiana</td>
<td align="right">678</td>
<td align="right">0</td>
<td align="left">2000–2026</td>
</tr>
<tr class="odd">
<td align="left">Euterpe edulis</td>
<td align="right">4038</td>
<td align="right">0</td>
<td align="left">2000–2026</td>
</tr>
<tr class="even">
<td align="left">Paubrasilia echinata</td>
<td align="right">930</td>
<td align="right">0</td>
<td align="left">2000–2026</td>
</tr>
</tbody>
</table>
<p>Foram recuperados <strong>8.417 registros</strong>. A validação das
coordenadas excluiu 0 registros. A seleção climática não repete o filtro
temporal da etapa 4: inclui os tipos de registro conservados na limpeza
e admite ano ausente. Coordenadas históricas são tratadas como locais
documentados, não como confirmação de ocupação atual.</p>
</div>
<div id="mapas-climáticos-e-preparação-espacial" class="section level1">
<h1>Mapas climáticos e preparação espacial</h1>
<p>Os arquivos utilizados têm resolução de <strong>30 segundos de
arco</strong> (<code>0,008333…°</code>, aproximadamente 1 km). O projeto
inclui cópias integrais dos dois rasters globais de origem, sem recorte
ou reamostragem. Essa escolha conserva também a referência exata da
grade para coordenadas situadas nos limites das células.</p>
<p>Antes da extração, o código verifica se os rasters têm o mesmo
sistema de coordenadas, extensão e resolução. Cada ponto recebe a classe
da célula correspondente, sem interpolação. Valores fora dos códigos
1–30 são tratados como ausência de informação. A legenda é lida no
formato original <code>código: símbolo</code>.</p>
<pre class="r"><code>tab(data.frame(
  Periodo=c(&quot;1991–2020&quot;,&quot;2071–2099&quot;),
  Cenario=c(&quot;Referência histórica&quot;,&quot;SSP5-8.5&quot;),
  Resolucao_graus=c(terra::res(z$atual)[1],terra::res(z$futuro)[1])
), digits=7)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Periodo</th>
<th align="left">Cenario</th>
<th align="right">Resolucao_graus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1991–2020</td>
<td align="left">Referência histórica</td>
<td align="right">0.0083333</td>
</tr>
<tr class="even">
<td align="left">2071–2099</td>
<td align="left">SSP5-8.5</td>
<td align="right">0.0083333</td>
</tr>
</tbody>
</table>
<details>
<summary>
Consultar o código completo de carga, extração e verificação
</summary>
<pre class="r"><code>calcular05 &lt;- function() {
  p &lt;- caminho(&quot;data&quot;,&quot;kg_1991_2020_30s.tif&quot;)
  f &lt;- caminho(&quot;data&quot;,&quot;kg_2071_2099_ssp585_30s.tif&quot;)
  if (!all(file.exists(c(p,f)))) stop(&quot;Faltam os dois rasters globais em data/.&quot;)
  atual &lt;- terra::rast(p); futuro &lt;- terra::rast(f)
  terra::compareGeom(atual,futuro,stopOnError=TRUE)
  stopifnot(terra::nlyr(atual)==1L,terra::nlyr(futuro)==1L,
            all(abs(terra::res(atual)-1/120)&lt;1e-7))
  linhas &lt;- readLines(caminho(&quot;data&quot;,&quot;legend.txt&quot;),warn=FALSE,encoding=&quot;UTF-8&quot;)
  pat &lt;- &quot;^\\s*([0-9]+):\\s+([A-Za-z]+)\\s+.*$&quot;
  linhas &lt;- linhas[grepl(pat,linhas,perl=TRUE)]
  legenda &lt;- data.frame(codigo=as.integer(sub(pat,&quot;\\1&quot;,linhas,perl=TRUE)),
                        simbolo=sub(pat,&quot;\\2&quot;,linhas,perl=TRUE))
  stopifnot(nrow(legenda)==30L,setequal(legenda$codigo,1:30),!anyDuplicated(legenda$codigo))
  d &lt;- as.data.frame(readRDS(caminho(&quot;data&quot;,&quot;ocorrencias_alvo_etapa03.rds&quot;)))
  exigidas &lt;- c(&quot;gbifID&quot;,&quot;species&quot;,&quot;bioma&quot;,&quot;decimalLongitude&quot;,&quot;decimalLatitude&quot;)
  if(!all(exigidas %in% names(d))) stop(&quot;Colunas ausentes: &quot;,paste(setdiff(exigidas,names(d)),collapse=&quot;, &quot;))
  if(anyNA(d$bioma) || any(d$bioma != &quot;Mata Atlântica&quot;)) stop(&quot;A entrada contem registros de outro bioma.&quot;)
  # Compatibilidade explicita com o nome historico usado no documento anterior.
  d$nome_original &lt;- d$species
  d$species[d$species==&quot;Caesalpinia echinata&quot;] &lt;- &quot;Paubrasilia echinata&quot;
  alvos &lt;- c(&quot;Araucaria angustifolia&quot;,&quot;Cariniana legalis&quot;,&quot;Cattleya labiata&quot;,
              &quot;Dicksonia sellowiana&quot;,&quot;Euterpe edulis&quot;,&quot;Paubrasilia echinata&quot;)
  if (any(!d$species %in% alvos)) stop(&quot;Especie fora da lista de estudo.&quot;)
  n_origem &lt;- nrow(d)
  coordenadas_validas &lt;- with(d,is.finite(decimalLongitude)&amp;is.finite(decimalLatitude)&amp;
                                abs(decimalLongitude)&lt;=180&amp;abs(decimalLatitude)&lt;=90)
  auditoria &lt;- d[!coordenadas_validas, c(&quot;gbifID&quot;,&quot;species&quot;)]
  salvar_csv(auditoria,&quot;05_coordenadas_invalidas.csv&quot;)
  d &lt;- d[coordenadas_validas,]
  if(!nrow(d)) stop(&quot;Nenhum registro com coordenadas validas.&quot;)
  pontos &lt;- sf::st_as_sf(d,coords=c(&quot;decimalLongitude&quot;,&quot;decimalLatitude&quot;),crs=4326,remove=FALSE)
  pontos &lt;- sf::st_transform(pontos,terra::crs(atual))
  xy &lt;- sf::st_coordinates(pontos)
  # Matriz de coordenadas: extract devolve a camada, sem a coluna ID de SpatVector.
  d$kg_atual &lt;- as.integer(terra::extract(atual,xy)[[1]])
  d$kg_futuro &lt;- as.integer(terra::extract(futuro,xy)[[1]])
  d$kg_atual[!d$kg_atual %in% 1:30] &lt;- NA_integer_
  d$kg_futuro[!d$kg_futuro %in% 1:30] &lt;- NA_integer_
  d$celula &lt;- terra::cellFromXY(atual,xy)
  d$classe_atual &lt;- legenda$simbolo[match(d$kg_atual,legenda$codigo)]
  d$classe_futura &lt;- legenda$simbolo[match(d$kg_futuro,legenda$codigo)]
  d$situacao &lt;- ifelse(is.na(d$kg_atual)|is.na(d$kg_futuro),&quot;Sem informação climática&quot;,
                        ifelse(d$kg_atual==d$kg_futuro,&quot;Classe mantida&quot;,&quot;Classe alterada&quot;))
  resumir &lt;- function(x) {
    r &lt;- lapply(alvos,function(s) {
      a &lt;- x[x$species==s,,drop=FALSE]
      validos &lt;- sum(a$situacao!=&quot;Sem informação climática&quot;)
      muda &lt;- sum(a$situacao==&quot;Classe alterada&quot;)
      data.frame(species=s,total=nrow(a),validos=validos,sem_clima=nrow(a)-validos,
                  mantidos=sum(a$situacao==&quot;Classe mantida&quot;),alterados=muda,
                  percentual=if(validos&gt;0)100*muda/validos else NA_real_)
    })
    do.call(rbind,r)
  }
  resumo &lt;- resumir(d)
  # Uma observacao por especie e celula, apenas onde ha clima nos dois periodos.
  validos &lt;- d[d$situacao!=&quot;Sem informação climática&quot;,]
  celulas &lt;- validos[!duplicated(validos[c(&quot;species&quot;,&quot;celula&quot;)]),]
  resumo_celulas &lt;- resumir(celulas)
  if(&quot;coordinateUncertaintyInMeters&quot; %in% names(d)) {
    u &lt;- suppressWarnings(as.numeric(d$coordinateUncertaintyInMeters))
    precisos &lt;- resumir(d[!is.na(u)&amp;u&gt;=0&amp;u&lt;=1000,])
    incerteza &lt;- data.frame(species=alvos,
      sem_incerteza=vapply(alvos,function(s)sum(d$species==s &amp; is.na(u)),integer(1)),
      acima_1km=vapply(alvos,function(s)sum(d$species==s &amp; !is.na(u) &amp; u&gt;1000),integer(1)))
  } else { precisos &lt;- NULL; incerteza &lt;- NULL }
  transicoes &lt;- as.data.frame(dplyr::count(validos,species,classe_atual,classe_futura,name=&quot;registros&quot;))
  transicoes$percentual &lt;- 100*transicoes$registros/resumo$validos[match(transicoes$species,resumo$species)]
  transicoes &lt;- transicoes[order(transicoes$species,-transicoes$registros),]
  sensibilidade &lt;- merge(resumo[c(&quot;species&quot;,&quot;validos&quot;,&quot;percentual&quot;)],
                         resumo_celulas[c(&quot;species&quot;,&quot;validos&quot;,&quot;percentual&quot;)],by=&quot;species&quot;,suffixes=c(&quot;_registros&quot;,&quot;_celulas&quot;))
  sensibilidade$diferenca_pp &lt;- sensibilidade$percentual_celulas-sensibilidade$percentual_registros
  salvar_csv(resumo,&quot;05_resumo_especies.csv&quot;)
  salvar_csv(transicoes,&quot;05_transicoes_climaticas.csv&quot;)
  salvar_csv(sensibilidade,&quot;05_sensibilidade_celulas.csv&quot;)
  if(!is.null(precisos)) salvar_csv(precisos,&quot;05_sensibilidade_incerteza_1km.csv&quot;)
  if(!is.null(incerteza)) salvar_csv(incerteza,&quot;05_incerteza_coordenadas.csv&quot;)
  salvar_csv(d,&quot;05_ocorrencias_com_clima.csv&quot;)
  espacial &lt;- sf::st_as_sf(d,coords=c(&quot;decimalLongitude&quot;,&quot;decimalLatitude&quot;),crs=4326,remove=FALSE)
  sf::st_write(espacial,caminho(&quot;resultados&quot;,&quot;05_ocorrencias_clima.gpkg&quot;),layer=&quot;ocorrencias&quot;,delete_layer=TRUE,quiet=TRUE)
  list(dados=d,resumo=resumo,celulas=celulas,sensibilidade=sensibilidade,
        precisos=precisos,incerteza=incerteza,transicoes=transicoes,legenda=legenda,
        n_origem=n_origem,n_invalidas=nrow(auditoria),atual=atual,futuro=futuro)
}
</code></pre>
</details>
</div>
<div id="registros-com-informação-nos-dois-períodos"
class="section level1">
<h1>Registros com informação nos dois períodos</h1>
<p>O percentual de alteração usa como denominador apenas os registros
com classe válida no presente e no futuro. Os demais permanecem na
tabela de controle e no arquivo de ocorrências; não são classificados
como estáveis.</p>
<pre class="r"><code>tab(r,col.names=c(&quot;Espécie&quot;,&quot;Total&quot;,&quot;Clima válido&quot;,&quot;Sem clima&quot;,&quot;Mantidos&quot;,&quot;Alterados&quot;,&quot;Alteração (%)&quot;))</code></pre>
<table>
<colgroup>
<col width="27%" />
<col width="7%" />
<col width="15%" />
<col width="11%" />
<col width="10%" />
<col width="11%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Espécie</th>
<th align="right">Total</th>
<th align="right">Clima válido</th>
<th align="right">Sem clima</th>
<th align="right">Mantidos</th>
<th align="right">Alterados</th>
<th align="right">Alteração (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Araucaria angustifolia</td>
<td align="right">2534</td>
<td align="right">2534</td>
<td align="right">0</td>
<td align="right">472</td>
<td align="right">2062</td>
<td align="right">81.37</td>
</tr>
<tr class="even">
<td align="left">Cariniana legalis</td>
<td align="right">220</td>
<td align="right">220</td>
<td align="right">0</td>
<td align="right">120</td>
<td align="right">100</td>
<td align="right">45.45</td>
</tr>
<tr class="odd">
<td align="left">Cattleya labiata</td>
<td align="right">17</td>
<td align="right">17</td>
<td align="right">0</td>
<td align="right">13</td>
<td align="right">4</td>
<td align="right">23.53</td>
</tr>
<tr class="even">
<td align="left">Dicksonia sellowiana</td>
<td align="right">678</td>
<td align="right">678</td>
<td align="right">0</td>
<td align="right">191</td>
<td align="right">487</td>
<td align="right">71.83</td>
</tr>
<tr class="odd">
<td align="left">Euterpe edulis</td>
<td align="right">4038</td>
<td align="right">4037</td>
<td align="right">1</td>
<td align="right">1274</td>
<td align="right">2763</td>
<td align="right">68.44</td>
</tr>
<tr class="even">
<td align="left">Paubrasilia echinata</td>
<td align="right">930</td>
<td align="right">921</td>
<td align="right">9</td>
<td align="right">563</td>
<td align="right">358</td>
<td align="right">38.87</td>
</tr>
</tbody>
</table>
<p>Há informação climática nos dois períodos para <strong>8.407 de 8.417
registros (99,9%)</strong>. Os <strong>10 registros restantes</strong>
não entram no cálculo dos percentuais.</p>
</div>
<div id="exposição-por-espécie" class="section level1">
<h1>Exposição por espécie</h1>
<pre class="r"><code>barras &lt;- bind_rows(
  r |&gt; transmute(species,situacao=&quot;Classe mantida&quot;,percentual=100*mantidos/ifelse(validos&gt;0,validos,NA)),
  r |&gt; transmute(species,situacao=&quot;Classe alterada&quot;,percentual=100*alterados/ifelse(validos&gt;0,validos,NA)))
barras$species &lt;- factor(barras$species,levels=r$species[order(r$percentual)])
ggplot(barras,aes(species,percentual,fill=situacao)) + geom_col(width=.7) + coord_flip() +
  scale_fill_manual(values=c(&quot;Classe mantida&quot;=&quot;#287d79&quot;,&quot;Classe alterada&quot;=&quot;#bf603b&quot;)) +
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,25)) +
  labs(x=NULL,y=&quot;Registros com clima válido (%)&quot;,fill=NULL) + tema() +
  theme(axis.text.y=element_text(face=&quot;italic&quot;))</code></pre>
<div class="figure">
<img src="05_mudanca_climatica_mata_atlantica_files/figure-html/barras-1.png" alt="Proporção de registros com manutenção ou alteração da classe climática. O denominador de cada espécie aparece na tabela de cobertura; registros sem informação climática não entram nas barras." width="1350" />
<p class="caption">
Proporção de registros com manutenção ou alteração da classe climática.
O denominador de cada espécie aparece na tabela de cobertura; registros
sem informação climática não entram nas barras.
</p>
</div>
<p>A maior proporção de alteração ocorre em <strong><em>Araucaria
angustifolia</em></strong>: <strong>81,4%</strong> dos seus 2.534
registros com clima válido. No outro extremo, <strong><em>Cattleya
labiata</em></strong> apresenta <strong>23,5%</strong>, calculados sobre
17 registros. A diferença indica exposição desigual entre as localidades
representadas para essas espécies, sem estabelecer, por si só, uma ordem
de vulnerabilidade biológica.</p>
<ul>
<li><strong><em>Araucaria angustifolia</em></strong>: 2.062 de 2.534
registros com clima válido apresentam alteração
(<strong>81,4%</strong>).</li>
<li><strong><em>Cariniana legalis</em></strong>: 100 de 220 registros
com clima válido apresentam alteração (<strong>45,5%</strong>).</li>
<li><strong><em>Cattleya labiata</em></strong>: 4 de 17 registros com
clima válido apresentam alteração (<strong>23,5%</strong>).</li>
<li><strong><em>Dicksonia sellowiana</em></strong>: 487 de 678 registros
com clima válido apresentam alteração (<strong>71,8%</strong>).</li>
<li><strong><em>Euterpe edulis</em></strong>: 2.763 de 4.037 registros
com clima válido apresentam alteração (<strong>68,4%</strong>).</li>
<li><strong><em>Paubrasilia echinata</em></strong>: 358 de 921 registros
com clima válido apresentam alteração (<strong>38,9%</strong>).</li>
</ul>
<p>Uma proporção elevada aponta para a necessidade de examinar o clima
das populações documentadas com maior detalhe. Entretanto, a resposta de
cada espécie também depende de tolerâncias fisiológicas, dispersão,
microclima e condições do habitat. A manutenção da classe tampouco
implica clima constante: temperatura e precipitação podem variar sem
ultrapassar os limites da classificação.</p>
</div>
<div id="distribuição-espacial-da-exposição" class="section level1">
<h1>Distribuição espacial da exposição</h1>
<pre class="r"><code>limite &lt;- readRDS(caminho(&quot;data&quot;,&quot;biomas_2025.rds&quot;)) |&gt;
  st_transform(5880) |&gt; st_simplify(dTolerance=1000,preserveTopology=TRUE) |&gt; st_transform(4326)
limite &lt;- limite[limite$name_biome==&quot;Mata Atlântica&quot;,]
ggplot() + geom_sf(data=limite,fill=&quot;#eef1e9&quot;,color=&quot;#879488&quot;,linewidth=.2) +
  geom_point(data=d,aes(decimalLongitude,decimalLatitude,color=situacao),size=.65,alpha=.65) +
  facet_wrap(~species,ncol=3) +
  scale_color_manual(values=c(&quot;Classe mantida&quot;=&quot;#287d79&quot;,&quot;Classe alterada&quot;=&quot;#bf603b&quot;,
                              &quot;Sem informação climática&quot;=&quot;#777777&quot;),drop=FALSE) +
  coord_sf(xlim=c(-56,-34),ylim=c(-34,-3),expand=FALSE) +
  scale_x_continuous(breaks=c(-50,-40)) + scale_y_continuous(breaks=c(-30,-20,-10)) +
  labs(x=NULL,y=NULL,color=NULL) + tema() + theme(strip.text=element_text(face=&quot;italic&quot;))</code></pre>
<div class="figure">
<img src="05_mudanca_climatica_mata_atlantica_files/figure-html/mapa-exposicao-1.png" alt="Localidades documentadas na Mata Atlântica, classificadas pela mudança climática projetada. Pontos sobrepostos podem ocultar a repetição de registros." width="1350" />
<p class="caption">
Localidades documentadas na Mata Atlântica, classificadas pela mudança
climática projetada. Pontos sobrepostos podem ocultar a repetição de
registros.
</p>
</div>
<p>O mapa permite localizar concentrações de registros expostos e
reconhecer áreas pouco representadas. Uma concentração de pontos não
demonstra maior densidade populacional, pois a base reúne amostragens
heterogêneas. Da mesma forma, espaços sem pontos não comprovam ausência
da espécie.</p>
</div>
<div id="quais-classes-substituem-as-atuais" class="section level1">
<h1>Quais classes substituem as atuais?</h1>
<pre class="r"><code>principais &lt;- z$transicoes |&gt;
  filter(classe_atual!=classe_futura) |&gt;
  group_by(species) |&gt; slice_max(registros,n=3,with_ties=FALSE) |&gt; ungroup()
tab(principais,col.names=c(&quot;Espécie&quot;,&quot;Classe atual&quot;,&quot;Classe futura&quot;,&quot;Registros&quot;,&quot;% dos registros válidos&quot;))</code></pre>
<table>
<colgroup>
<col width="27%" />
<col width="15%" />
<col width="16%" />
<col width="11%" />
<col width="28%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Espécie</th>
<th align="left">Classe atual</th>
<th align="left">Classe futura</th>
<th align="right">Registros</th>
<th align="right">% dos registros válidos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Araucaria angustifolia</td>
<td align="left">Cfb</td>
<td align="left">Cfa</td>
<td align="right">1415</td>
<td align="right">55.84</td>
</tr>
<tr class="even">
<td align="left">Araucaria angustifolia</td>
<td align="left">Cfa</td>
<td align="left">Af</td>
<td align="right">179</td>
<td align="right">7.06</td>
</tr>
<tr class="odd">
<td align="left">Araucaria angustifolia</td>
<td align="left">Cfa</td>
<td align="left">Am</td>
<td align="right">135</td>
<td align="right">5.33</td>
</tr>
<tr class="even">
<td align="left">Cariniana legalis</td>
<td align="left">Cfa</td>
<td align="left">Aw</td>
<td align="right">36</td>
<td align="right">16.36</td>
</tr>
<tr class="odd">
<td align="left">Cariniana legalis</td>
<td align="left">Af</td>
<td align="left">Aw</td>
<td align="right">12</td>
<td align="right">5.45</td>
</tr>
<tr class="even">
<td align="left">Cariniana legalis</td>
<td align="left">Cwa</td>
<td align="left">Aw</td>
<td align="right">12</td>
<td align="right">5.45</td>
</tr>
<tr class="odd">
<td align="left">Cattleya labiata</td>
<td align="left">Am</td>
<td align="left">Aw</td>
<td align="right">2</td>
<td align="right">11.76</td>
</tr>
<tr class="even">
<td align="left">Cattleya labiata</td>
<td align="left">Cfa</td>
<td align="left">Aw</td>
<td align="right">1</td>
<td align="right">5.88</td>
</tr>
<tr class="odd">
<td align="left">Cattleya labiata</td>
<td align="left">Cwa</td>
<td align="left">Aw</td>
<td align="right">1</td>
<td align="right">5.88</td>
</tr>
<tr class="even">
<td align="left">Dicksonia sellowiana</td>
<td align="left">Cfb</td>
<td align="left">Cfa</td>
<td align="right">371</td>
<td align="right">54.72</td>
</tr>
<tr class="odd">
<td align="left">Dicksonia sellowiana</td>
<td align="left">Cfa</td>
<td align="left">Af</td>
<td align="right">46</td>
<td align="right">6.78</td>
</tr>
<tr class="even">
<td align="left">Dicksonia sellowiana</td>
<td align="left">Cfa</td>
<td align="left">Aw</td>
<td align="right">12</td>
<td align="right">1.77</td>
</tr>
<tr class="odd">
<td align="left">Euterpe edulis</td>
<td align="left">Cfb</td>
<td align="left">Cfa</td>
<td align="right">1819</td>
<td align="right">45.06</td>
</tr>
<tr class="even">
<td align="left">Euterpe edulis</td>
<td align="left">Cfa</td>
<td align="left">Af</td>
<td align="right">376</td>
<td align="right">9.31</td>
</tr>
<tr class="odd">
<td align="left">Euterpe edulis</td>
<td align="left">Am</td>
<td align="left">Af</td>
<td align="right">183</td>
<td align="right">4.53</td>
</tr>
<tr class="even">
<td align="left">Paubrasilia echinata</td>
<td align="left">Am</td>
<td align="left">Aw</td>
<td align="right">88</td>
<td align="right">9.55</td>
</tr>
<tr class="odd">
<td align="left">Paubrasilia echinata</td>
<td align="left">Af</td>
<td align="left">Aw</td>
<td align="right">87</td>
<td align="right">9.45</td>
</tr>
<tr class="even">
<td align="left">Paubrasilia echinata</td>
<td align="left">Cfa</td>
<td align="left">Aw</td>
<td align="right">38</td>
<td align="right">4.13</td>
</tr>
</tbody>
</table>
<p>A combinação espécie–transição com mais registros é <strong>Cfb → Cfa
em <em>Euterpe edulis</em></strong>, com <strong>1.819
registros</strong>. Essa frequência se refere ao conjunto amostrado e
pode ser influenciada pela repetição de localidades.</p>
<p>As letras representam categorias climáticas, não uma escala linear de
deterioração ambiental. A tabela identifica quais mudanças merecem
investigação, mas não quantifica diretamente o aquecimento, a alteração
da precipitação ou a adequação do habitat. Essas perguntas exigem
examinar as variáveis climáticas contínuas que sustentam a classificação
(Beck et al., 2023).</p>
</div>
<div id="efeito-da-repetição-espacial" class="section level1">
<h1>Efeito da repetição espacial</h1>
<p>Ocorrências da mesma espécie podem ocupar a mesma célula e, portanto,
repetir a mesma comparação climática. A análise abaixo conserva uma
observação por espécie e célula com clima válido. Ela reduz o peso da
repetição dentro da grade, mas não corrige lacunas de amostragem ou
autocorrelação entre células vizinhas.</p>
<pre class="r"><code>tab(z$sensibilidade,col.names=c(&quot;Espécie&quot;,&quot;Registros válidos&quot;,&quot;Alteração por registros (%)&quot;,
                               &quot;Células válidas&quot;,&quot;Alteração por células (%)&quot;,&quot;Diferença (p.p.)&quot;))</code></pre>
<table>
<colgroup>
<col width="17%" />
<col width="14%" />
<col width="21%" />
<col width="12%" />
<col width="20%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Espécie</th>
<th align="right">Registros válidos</th>
<th align="right">Alteração por registros (%)</th>
<th align="right">Células válidas</th>
<th align="right">Alteração por células (%)</th>
<th align="right">Diferença (p.p.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Araucaria angustifolia</td>
<td align="right">2534</td>
<td align="right">81.37</td>
<td align="right">1461</td>
<td align="right">77.75</td>
<td align="right">-3.62</td>
</tr>
<tr class="even">
<td align="left">Cariniana legalis</td>
<td align="right">220</td>
<td align="right">45.45</td>
<td align="right">176</td>
<td align="right">43.75</td>
<td align="right">-1.70</td>
</tr>
<tr class="odd">
<td align="left">Cattleya labiata</td>
<td align="right">17</td>
<td align="right">23.53</td>
<td align="right">16</td>
<td align="right">25.00</td>
<td align="right">1.47</td>
</tr>
<tr class="even">
<td align="left">Dicksonia sellowiana</td>
<td align="right">678</td>
<td align="right">71.83</td>
<td align="right">444</td>
<td align="right">69.82</td>
<td align="right">-2.01</td>
</tr>
<tr class="odd">
<td align="left">Euterpe edulis</td>
<td align="right">4037</td>
<td align="right">68.44</td>
<td align="right">650</td>
<td align="right">66.92</td>
<td align="right">-1.52</td>
</tr>
<tr class="even">
<td align="left">Paubrasilia echinata</td>
<td align="right">921</td>
<td align="right">38.87</td>
<td align="right">550</td>
<td align="right">41.09</td>
<td align="right">2.22</td>
</tr>
</tbody>
</table>
<p>A maior diferença entre as duas formas de contagem ocorre em
<strong><em>Araucaria angustifolia</em></strong>: de <strong>81,4% por
registro</strong> para <strong>77,8% por célula</strong>, uma diferença
de <strong>-3,6 pontos percentuais</strong>. Esse contraste mostra
quanto o resultado depende da distribuição dos registros entre as
células ocupadas.</p>
</div>
<div id="incerteza-das-coordenadas" class="section level1">
<h1>Incerteza das coordenadas</h1>
<p>Uma coordenada com incerteza superior à dimensão aproximada da célula
pode representar locais com classes diferentes. Por isso, apresentamos
uma análise adicional restrita aos registros com incerteza declarada
entre 0 e 1.000 m. O valor zero é mantido conforme informado na base,
sem ser interpretado como prova de localização exata. Registros sem
estimativa de incerteza não entram nesse subconjunto.</p>
<pre class="r"><code>if(!is.null(z$incerteza)) tab(z$incerteza,col.names=c(&quot;Espécie&quot;,&quot;Incerteza não informada&quot;,&quot;Incerteza &gt; 1 km&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Espécie</th>
<th align="right">Incerteza não informada</th>
<th align="right">Incerteza &gt; 1 km</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Araucaria angustifolia</td>
<td align="right">695</td>
<td align="right">280</td>
</tr>
<tr class="even">
<td align="left">Cariniana legalis</td>
<td align="right">132</td>
<td align="right">83</td>
</tr>
<tr class="odd">
<td align="left">Cattleya labiata</td>
<td align="right">10</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">Dicksonia sellowiana</td>
<td align="right">469</td>
<td align="right">209</td>
</tr>
<tr class="odd">
<td align="left">Euterpe edulis</td>
<td align="right">3559</td>
<td align="right">475</td>
</tr>
<tr class="even">
<td align="left">Paubrasilia echinata</td>
<td align="right">592</td>
<td align="right">332</td>
</tr>
</tbody>
</table>
<pre class="r"><code>if(!is.null(z$precisos)) tab(z$precisos,col.names=c(&quot;Espécie&quot;,&quot;Total ≤ 1 km&quot;,&quot;Clima válido&quot;,&quot;Sem clima&quot;,&quot;Mantidos&quot;,&quot;Alterados&quot;,&quot;Alteração (%)&quot;))</code></pre>
<table>
<colgroup>
<col width="25%" />
<col width="14%" />
<col width="14%" />
<col width="10%" />
<col width="9%" />
<col width="10%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Espécie</th>
<th align="right">Total ≤ 1 km</th>
<th align="right">Clima válido</th>
<th align="right">Sem clima</th>
<th align="right">Mantidos</th>
<th align="right">Alterados</th>
<th align="right">Alteração (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Araucaria angustifolia</td>
<td align="right">1559</td>
<td align="right">1559</td>
<td align="right">0</td>
<td align="right">280</td>
<td align="right">1279</td>
<td align="right">82.04</td>
</tr>
<tr class="even">
<td align="left">Cariniana legalis</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">Cattleya labiata</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Dicksonia sellowiana</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="left">Euterpe edulis</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">100.00</td>
</tr>
<tr class="even">
<td align="left">Paubrasilia echinata</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">0.00</td>
</tr>
</tbody>
</table>
<p>Percentuais baseados em poucos registros são sensíveis à inclusão ou
exclusão de poucas localidades. Isso é especialmente relevante para
espécies menos representadas neste conjunto. A análise de sensibilidade
não substitui a revisão das coordenadas nem comprova a precisão
declarada.</p>
<p>No subconjunto com incerteza declarada de até 1 km, há menos de dez
registros válidos para <em>Cariniana legalis</em> (n = 5), <em>Cattleya
labiata</em> (n = 0), <em>Dicksonia sellowiana</em> (n = 0), <em>Euterpe
edulis</em> (n = 4), <em>Paubrasilia echinata</em> (n = 6). Nesses
casos, percentuais de 0% ou 100% não demonstram estabilidade ou
alteração generalizada; refletem um subconjunto insuficiente para
sustentar essa interpretação. Quando n = 0, o percentual não é
calculado.</p>
</div>
<div id="interpretação-ecológica" class="section level1">
<h1>Interpretação ecológica</h1>
<p><strong>Gráfico de barras</strong></p>
<p>O padrão é claro e ecologicamente coerente: as espécies com maior
proporção de alteração climática projetada são <em>Araucaria
angustifolia</em> (81,4%) e <em>Dicksonia sellowiana</em> (71,8%),
seguidas por <em>Euterpe edulis</em> (68,4%). No outro extremo,
<em>Paubrasilia echinata</em> (38,9%) e <em>Cariniana legalis</em>
(45,5%) apresentam menor exposição, enquanto <em>Cattleya labiata</em>
(23,5%) apresenta o menor valor entre todas. No entanto, como esta
última espécie possui apenas 17 registros, esse resultado apresenta
baixa robustez estatística.</p>
<p>Esse padrão é biogeograficamente coerente: <em>Araucaria</em> e
<em>Dicksonia</em> são táxons associados a climas
temperados/subtropicais de altitude, especialmente do tipo Cfb,
correspondente ao clima oceânico temperado úmido. A transição dominante
detectada (Cfb→Cfa, isto é, de clima temperado úmido para subtropical
úmido com verões quentes) corresponde ao tipo de deslocamento climático
esperado sob cenários de aquecimento em regiões de maior latitude e
altitude no sul do Brasil. Espécies com distribuição associada a
condições mais tropicais, como <em>Paubrasilia</em>, presente em regiões
atualmente classificadas como Aw/Am, apresentam menor proporção de
mudança de classe climática por já ocorrerem em categorias
climaticamente mais quentes.</p>
<p><strong>Mapa de distribuição espacial</strong></p>
<p>O mapa permite identificar onde essa exposição se concentra. O padrão
é mais evidente nas regiões Sul e Sudeste, especialmente em áreas
atualmente classificadas como Cfb, onde a transição para Cfa é mais
generalizada. Em contraste, localidades já inseridas em climas tropicais
Af, Am ou Aw apresentam maior proporção de pontos com manutenção da
classe climática.</p>
<p>Esse resultado sugere a existência de um gradiente latitudinal e
altitudinal de exposição às mudanças climáticas, em vez de uma resposta
homogênea ao longo de toda a Mata Atlântica. . # Produtos e
rastreabilidade</p>
<p>O código salva o resumo por espécie, as transições, as análises de
sensibilidade e as ocorrências com clima na pasta
<code>resultados/</code>. A versão espacial é
<code>05_ocorrencias_clima.gpkg</code>. O site oferece apenas as tabelas
sintéticas em <a href="resultados.html">Resultados</a>; as entradas
compactas e o código acompanham o projeto.</p>
<pre><code>## R version 4.4.1 (2024-06-14 ucrt)
## Platform: x86_64-w64-mingw32/x64
## Running under: Windows 11 x64 (build 26200)
## 
## Matrix products: default
## 
## 
## locale:
## [1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8   
## [3] LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C                      
## [5] LC_TIME=Portuguese_Brazil.utf8    
## 
## time zone: America/Sao_Paulo
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] leaflet_2.2.3 sf_1.1-0      dplyr_1.1.4   ggplot2_4.0.3
## 
## loaded via a namespace (and not attached):
##  [1] sass_0.4.9              utf8_1.2.4              generics_0.1.3          class_7.3-22           
##  [5] KernSmooth_2.23-24      digest_0.6.36           magrittr_2.0.3          evaluate_0.24.0        
##  [9] grid_4.4.1              RColorBrewer_1.1-3      nanoarrow_0.8.0         rnaturalearth_1.2.0    
## [13] fastmap_1.2.0           jsonlite_1.8.8          e1071_1.7-14            DBI_1.2.3              
## [17] fansi_1.0.6             crosstalk_1.2.1         viridisLite_0.4.2       scales_1.4.0           
## [21] codetools_0.2-20        jquerylib_0.1.4         cli_3.6.3               rlang_1.1.4            
## [25] units_0.8-5             withr_3.0.0             cachem_1.1.0            yaml_2.3.12            
## [29] geobr_2.0.1             tools_4.4.1             geoarrow_0.4.2          curl_5.2.1             
## [33] vctrs_0.6.5             R6_2.5.1                proxy_0.4-27            lifecycle_1.0.5        
## [37] classInt_0.4-10         leaflet.providers_3.0.0 htmlwidgets_1.6.4       pkgconfig_2.0.3        
## [41] terra_1.9-11            pillar_1.9.0            bslib_0.7.0             gtable_0.3.6           
## [45] data.table_1.15.4       glue_1.7.0              Rcpp_1.0.12             xfun_0.45              
## [49] tibble_3.2.1            tidyselect_1.2.1        highr_0.11              rstudioapi_0.16.0      
## [53] knitr_1.48              farver_2.1.2            htmltools_0.5.8.1       rmarkdown_2.27         
## [57] labeling_0.4.3          wk_0.9.2                compiler_4.4.1          S7_0.2.1</code></pre>
</div>
<div id="referências" class="section level1">
<h1>Referências</h1>
<p>Beck, H. E., McVicar, T. R., Vergopolan, N., Berg, A., Lutsko, N. J.,
Dufour, A., Zeng, Z., Jiang, X., van Dijk, A. I. J. M., &amp; Miralles,
D. G. (2023). High-resolution (1 km) Köppen-Geiger maps for 1901–2099
based on constrained CMIP6 projections. <em>Scientific Data, 10</em>,
724. <a href="https://doi.org/10.1038/s41597-023-02549-6"
class="uri">https://doi.org/10.1038/s41597-023-02549-6</a></p>
<p>Meyer, C., Weigelt, P., &amp; Kreft, H. (2016). Multidimensional
biases, gaps and uncertainties in global plant occurrence information.
<em>Ecology Letters, 19</em>(8), 992–1006. <a
href="https://doi.org/10.1111/ele.12624"
class="uri">https://doi.org/10.1111/ele.12624</a></p>
<p>Royal Botanic Gardens, Kew. (2026). <em>Paubrasilia echinata (Lam.)
Gagnon, H.C.Lima &amp; G.P.Lewis</em>. Plants of the World Online.
Consultado em 15 de setembro de 2026, em <a
href="https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:77158012-1"
class="uri">https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:77158012-1</a>.
Sem DOI.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
